---
creation_rules:
  - path_regex: def/.*\.sops.ya?ml
    encrypted_regex: "^(macros)$"
    key_groups:
      - age:
          - age13srthcdyr08hp7w5xvezn5fex4p5kw7tky2pnrfef2u4j3uqsqgqwak9gc
  - path_regex: pre/.*\.sops.ya?ml
    encrypted_regex: "^(macros)$"
    key_groups:
      - age:
          - age13srthcdyr08hp7w5xvezn5fex4p5kw7tky2pnrfef2u4j3uqsqgqwak9gc

