---
name: Lint
description: Perform linting

inputs:
  token:
    description: GitHub token
    required: true

runs:
  using: composite

  steps:
    - name: MegaLinter
      uses: oxsecurity/megalinter@146333030da68e2e58c6ff826633824fabe01eaf # v8.5.0
      env:
        GITHUB_TOKEN: "${{ inputs.token }}"
        VALIDATE_ALL_CODEBASE: ${{ github.event_name == 'workflow_dispatch' }}
        ENABLE_LINTERS: |-
          ${{
            join(
              fromJSON('
                [
                  "ACTION_ACTIONLINT",
                  "REPOSITORY_GIT_DIFF",
                  "REPOSITORY_SECRETLINT",
                  "LATEX_CHKTEX"
                ]
              '),
              ','
            )
          }}
        LATEX_CHKTEX_CONFIG_FILE: .github/linters/.chktex.yaml
        LATEX_CHKTEX_ARGUMENTS: --nowarn 1 --nowarn 8 --nowarn 44
