---
name: Decrypt SOPS
description: Decrypt SOPS secrets

inputs:
  sops-key:
    description: SOPS private key
    required: true

runs:
  using: composite

  steps:
  - name: Download junction Font
    shell: bash
    run: |-
      # [junction](https://github.com/theleagueof/junction)
      URL="https://github.com/theleagueof/junction/archive/master.tar.gz"
      printf "Downloading %s\n" "${URL}" >&2
      curl --location --silent -- "${URL}" | tar --extract --gunzip
      mkdir --parents ./fonts/
      mv --no-clobber "./junction-master/" ./fonts/junction/

  - name: Download Libertinus Font
    shell: bash
    run: |-
      # [Libertinus](https://github.com/alerque/libertinus)
      RESPONSE=$(curl --silent --location "https://api.github.com/repos/alerque/libertinus/releases/latest")
      URL=$(printf "%s" "${RESPONSE}" | jq --raw-output ".assets[] | select(.content_type == "application/octet-stream").browser_download_url")
      FOLDER_NAME=$(basename -- "${URL}" .tar.zst)
      printf "Downloading %s\n" "${URL}" >&2
      curl --location --silent -- "${URL}" | tar --extract --use-compress-program=unzstd
      mkdir --parents ./fonts/
      mv --no-clobber "./${FOLDER_NAME}/static/OTF/" ./fonts/Libertinus/
      rm --recursive "./${FOLDER_NAME}"

  - name: Download SOPS
    shell: bash
    run: |-
      # [SOPS](https://github.com/mozilla/sops)
      SOPS_LATEST_VERSION=$(curl --silent --location "https://api.github.com/repos/mozilla/sops/releases/latest" | grep --perl-regexp --only-matching ""tag_name": "v\K[0-9.]+")
      curl --location --output sops.deb "https://github.com/mozilla/sops/releases/latest/download/sops_${SOPS_LATEST_VERSION}_amd64.deb"
      sudo apt --fix-broken install ./sops.deb

  - name: Decrypt Secrets
    shell: bash
    run: |-
      export SOPS_AGE_KEY=${{ inputs.sops-key }}
      ./gen.sh
