---
name: Lint

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - "def/*"
      - "doc/*"
      - "pre/*"

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  DEFAULT_BRANCH: main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download junction Font
        run: |-
          # [junction](https://github.com/theleagueof/junction)
          url="https://github.com/theleagueof/junction/archive/master.tar.gz"
          printf 'Downloading %s\n' "$url" >&2
          curl --location --silent -- "$url" | tar --extract --gunzip
          mkdir --parents ./fonts/
          mv --no-clobber "./junction-master/" ./fonts/junction/

      - name: Download Libertinus Font
        run: |-
          # [Libertinus](https://github.com/alerque/libertinus)
          response=$(curl --silent --location 'https://api.github.com/repos/alerque/libertinus/releases/latest')
          url=$(printf '%s' "$response" | jq --raw-output '.assets[] | select(.content_type == "application/x-xz").browser_download_url')
          foldername=$(basename -- "$url" .tar.xz)
          printf 'Downloading %s\n' "$url" >&2
          curl --location --silent -- "$url" | xz --decompress | tar --extract
          mkdir --parents ./fonts/
          mv --no-clobber "./$foldername/static/OTF/" ./fonts/Libertinus/
          rm --recursive "./$foldername"

      - name: Download SOPS
        run: |-
          # [SOPS](https://github.com/mozilla/sops)
          sops_latest_version=$(curl --silent --location "https://api.github.com/repos/mozilla/sops/releases/latest" | grep --perl-regexp --only-matching '"tag_name": "v\K[0-9.]+')
          curl --location --output sops.deb "https://github.com/mozilla/sops/releases/latest/download/sops_${sops_latest_version}_amd64.deb"
          sudo apt --fix-broken install ./sops.deb

      - name: Decrypt Secrets
        run: |-
          export SOPS_AGE_KEY=${{ secrets.AGE_SECRET_KEY }}
          ./gen.sh

      - name: MegaLinter
        uses: oxsecurity/megalinter@v6.22.2
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          VALIDATE_ALL_CODEBASE: ${{ github.event_name == 'workflow_dispatch' }}
          ENABLE_LINTERS: |-
            ${{
              join(
                fromJSON('
                  [
                    "ACTION_ACTIONLINT",
                    "REPOSITORY_GIT_DIFF",
                    "REPOSITORY_SECRETLINT",
                    "LATEX_CHKTEX"
                  ]
                '),
                ','
              )
            }}
          LATEX_CHKTEX_CONFIG_FILE: .github/linters/.chktex.yaml
          LATEX_CHKTEX_ARGUMENTS: --nowarn 1 --nowarn 8 --nowarn 44

