---
name: On Merge

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "def/*"
      - "doc/*"
      - "pre/*"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

      - name: Decrypt
        uses: ./.github/actions/decrypt-sops
        with:
          sops-key: "${{ secrets.AGE_SECRET_KEY }}"

      - name: Lint
        uses: ./.github/actions/lint
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"

  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

      - name: Decrypt
        uses: ./.github/actions/decrypt-sops
        with:
          sops-key: "${{ secrets.AGE_SECRET_KEY }}"

      - name: Upload
        uses: ./.github/actions/upload
        with:
          aws-access-key-id: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          aws-secret-access-key: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          aws-s3-endpoint: "${{ secrets.AWS_S3_ENDPOINT }}"
