---
name: On Merge

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "def/*"
      - "doc/*"
      - "pre/*"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4

      - name: Decrypt
        uses: ./.github/actions/decrypt-sops
        with:
          sops-key: "${{ secrets.AGE_SECRET_KEY }}"

      - name: Lint
        uses: ./.github/actions/lint
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"

  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4

      - name: Decrypt
        uses: ./.github/actions/decrypt-sops
        with:
          sops-key: "${{ secrets.AGE_SECRET_KEY }}"

      - name: Upload
        uses: ./.github/actions/upload
        with:
          nc-user: "${{ secrets.NEXTCLOUD_USERNAME }}"
          nc-pass: "${{ secrets.NEXTCLOUD_PASSWORD }}"
          nc-url: "${{ secrets.SECRET_NEXTCLOUD_URL }}"