---
name: On Pull Request

on:
  pull_request:
    branches:
      - main
    paths:
      - "def/*"
      - "doc/*"
      - "pre/*"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Decrypt
        uses: ./.github/actions/decrypt-sops
        with:
          sops-key: "${{ secrets.AGE_SECRET_KEY }}"

      - name: Lint
        uses: ./.github/actions/lint
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"