---
name: On Pull Request

on:
  pull_request:
    branches:
      - main
    paths:
      - "def/*"
      - "doc/*"
      - "pre/*"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

      - name: Decrypt
        uses: ./.github/actions/decrypt-sops
        with:
          sops-key: "${{ secrets.AGE_SECRET_KEY }}"

      - name: Lint
        uses: ./.github/actions/lint
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"