---
name: On Pull Request

on:
  pull_request:
    branches:
      - main
    paths:
      - "def/*"
      - "doc/*"
      - "pre/*"

env:
  DEFAULT_BRANCH: main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Decrypt
        uses: ./.github/actions/decrypt-sops
        with:
          sops-key: "${{ secrets.AGE_SECRET_KEY }}"

      - name: Lint
        uses: ./.github/actions/lint
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"